import type { Metadata } from "next";
import localFont from "next/font/local";
import { ThemeProvider } from "next-themes";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { Toaster } from "sonner";
import { Theme } from "@radix-ui/themes/components/index";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Messenger",
  description: "Generated by Anonymous!",
};

export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>
) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geistSans.className}`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Theme>
            {children}
            <Toaster />
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
